export const FroalaConfig = {
  language: "fr",
  height: 700,
  documentReady: true,
  // lineBreakerOffset: 5,
  tableCellStyles: {
    red: "Red",
    blue: "Blue",
    black: "Black",
    boldblack: "Black and Bold",
    extraboldblack: "Extra bold and black",
    "center-bold": "Centered and Bold",
  },
  wordAllowedStyleProps: [
    "font-family",
    "font-size",
    "background",
    "color",
    "width",
    "text-align",
    "vertical-align",
    "background-color",
    "padding",
    "margin",
    "height",
    "margin-top",
    "margin-left",
    "margin-right",
    "margin-bottom",
    "text-decoration",
    "font-weight",
    "font-style",
  ],
  toolbarButtons: [
    "bold",
    "italic",
    "underline",
    "strikeThrough",
    "subscript",
    "superscript",
    "fontFamily",
    "fontSize",
    "|",
    "specialCharacters",
    "color",
    // "emoticons",
    "inlineStyle",
    "paragraphStyle",
    "|",
    "paragraphFormat",
    "align",
    "formatOL",
    "formatUL",
    "outdent",
    "indent",
    "-",
    "quote",
    "insertHR",
    // "insertLink",
    "insertImage",
    // "insertVideo",
    // "insertFile",
    "insertTable",
    "|",
    "undo",
    "redo",
    "clearFormatting",
    "selectAll",
    "applyFormat",
    "removeFormat",
    "fullscreen",
    "print",
    "help",
  ],
};
