export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";


export const FETCH_CLIENT = 'FETCH_CLIENT';
export const CREATE_CLIENT = 'CREATE_CLIENT';
export const FETCH_CLIENTS = 'FETCH_CLIENTS';
export const DELETE_CLIENT = 'DELETE_CLIENT';


// export const FETCH_FOLDER = 'FETCH_FOLDER';
// export const CREATE_FOLDER = 'CREATE_FOLDER';
// export const FETCH_FOLDERS = 'FETCH_FOLDERS';
// export const DELETE_FOLDER = 'DELETE_FOLDER';

export const FECTH_USERS_SUCCESS = 'FECTH_USERS_SUCCESS';
export const FECTH_USERS_FAIL = 'FECTH_USERS_FAIL';
export const FECTH_USER_SUCCESS = 'FECTH_USER_SUCCESS';
export const FECTH_USER_FAIL = 'FECTH_USER_FAIL';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL';



export const FECTH_CLIENTS_SUCCESS = 'FECTH_CLIENTS_SUCCESS';
export const FECTH_CLIENTS_FAIL = 'FECTH_CLIENTS_FAIL';
export const CREATE_CLIENT_SUCCESS = 'CREATE_CLIENT_SUCCESS';
export const CREATE_CLIENT_FAIL = 'CREATE_CLIENT_FAIL';
export const UPDATE_CLIENT_SUCCESS = 'UPDATE_CLIENT_SUCCESS';
export const UPDATE_CLIENT_FAIL = 'UPDATE_CLIENT_FAIL';
export const DELETE_CLIENT_SUCCESS = 'DELETE_CLIENT_SUCCESS';
export const DELETE_CLIENT_FAIL = 'DELETE_CLIENT_FAIL';


export const FECTH_FOLDERS_SUCCESS = 'FECTH_FOLDERS_SUCCESS';
export const FECTH_FOLDERS_FAIL = 'FECTH_FOLDERS_FAIL';
export const FECTH_FOLDER_SUCCESS = 'FECTH_FOLDER_SUCCESS';
export const FECTH_FOLDER_FAIL = 'FECTH_FOLDER_FAIL';
export const CREATE_FOLDER_SUCCESS = 'CREATE_FOLDER_SUCCESS';
export const CREATE_FOLDER_FAIL = 'CREATE_FOLDER_FAIL';
export const UPDATE_FOLDER_SUCCESS = 'UPDATE_FOLDER_SUCCESS';
export const UPDATE_FOLDER_FAIL = 'UPDATE_FOLDER_FAIL';
export const DELETE_FOLDER_SUCCESS = 'DELETE_FOLDER_SUCCESS';
export const DELETE_FOLDER_FAIL = 'DELETE_FOLDER_FAIL';


export const FECTH_ACTES_SUCCESS = 'FECTH_ACTES_SUCCESS';
export const FECTH_ACTES_FAIL = 'FECTH_ACTES_FAIL';
export const FECTH_ACTE_SUCCESS = 'FECTH_ACTE_SUCCESS';
export const FECTH_ACTE_FAIL = 'FECTH_ACTE_FAIL';
export const FECTH_FOLDER_ACTE_SUCCESS = 'FECTH_FOLDER_ACTE_SUCCESS';
export const FECTH_FOLDER_ACTE_FAIL = 'FECTH_FOLDER_ACTE_FAIL';
export const CREATE_ACTE_SUCCESS = 'CREATE_ACTE_SUCCESS';
export const CREATE_ACTE_FAIL = 'CREATE_ACTE_FAIL';
export const UPDATE_ACTE_SUCCESS = 'UPDATE_ACTE_SUCCESS';
export const UPDATE_ACTE_FAIL = 'UPDATE_ACTE_FAIL';
export const DELETE_ACTE_SUCCESS = 'DELETE_ACTE_SUCCESS';
export const DELETE_ACTE_FAIL = 'DELETE_ACTE_FAIL';


export const FECTH_DMODELS_SUCCESS = 'FECTH_DMODELS_SUCCESS';
export const FECTH_DMODELS_FAIL = 'FECTH_DMODELS_FAIL';
export const FECTH_DMODEL_SUCCESS = 'FECTH_DMODEL_SUCCESS';
export const FECTH_DMODEL_FAIL = 'FECTH_DMODEL_FAIL';
export const FECTH_FOLDER_DMODELS_SUCCESS = 'FECTH_FOLDER_DMODELS_SUCCESS';
export const FECTH_FOLDER_DMODELS_FAIL = 'FECTH_FOLDER_DMODELS_FAIL';
export const CREATE_DMODEL_SUCCESS = 'CREATE_DMODEL_SUCCESS';
export const CREATE_DMODEL_FAIL = 'CREATE_DMODEL_FAIL';
export const UPDATE_DMODEL_SUCCESS = 'UPDATE_DMODEL_SUCCESS';
export const UPDATE_DMODEL_FAIL = 'UPDATE_DMODEL_FAIL';
export const DELETE_DMODEL_SUCCESS = 'DELETE_DMODEL_SUCCESS';
export const DELETE_DMODEL_FAIL = 'DELETE_DMODEL_FAIL';


export const FECTH_TASKS_SUCCESS = 'FECTH_TASKS_SUCCESS';
export const FECTH_TASKS_FAIL = 'FECTH_TASKS_FAIL';
export const FECTH_TASK_SUCCESS = 'FECTH_TASK_SUCCESS';
export const FECTH_TASK_FAIL = 'FECTH_TASK_FAIL';
export const FECTH_SENDER_TASK_SUCCESS = 'FECTH_SENDER_TASK_SUCCESS';
export const FECTH_SENDER_TASK_FAIL = 'FECTH_SENDER_TASK_FAIL';
export const FECTH_RECIEVER_TASK_SUCCESS = 'FECTH_RECIEVER_TASK_SUCCESS';
export const FECTH_RECIEVER_TASK_FAIL = 'FECTH_RECIEVER_TASK_FAIL';
export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS';
export const CREATE_TASK_FAIL = 'CREATE_TASK_FAIL';
export const UPDATE_TASK_SUCCESS = 'UPDATE_TASK_SUCCESS';
export const UPDATE_TASK_FAIL = 'UPDATE_TASK_FAIL';
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';
export const DELETE_TASK_FAIL = 'DELETE_TASK_FAIL';

